version: "3"
services:
  db:
    image: 'mongo:latest'
    volumes:
      - "./db:/data/db"
    ports:
      - "27017:27017"

  cms:
    build:
      context: cockpit
    environment:
      COCKPIT_SESSION_NAME: cockpit
      COCKPIT_SALT: _create_your_own_
      COCKPIT_DATABASE_SERVER: 'mongodb://db:27017'
      COCKPIT_DATABASE_NAME: cockpit_master
    depends_on:
      - db
    ports:
      - "8080:80"